import json
from app.models import LineageEvent, JobRef, RunRef, DatasetRef
from datetime import datetime, timezone
import uuid


def parse_manifest(manifest_path: str) -> list[LineageEvent]:
    """
    Parses a dbt manifest.json and returns one LineageEvent
    per model dependency relationship.

    The manifest.json is generated by running `dbt compile` or `dbt run`.
    It lives at target/manifest.json in the dbt project root.

    Logic:
    - Iterates all nodes, skips anything that is not a "model"
    - For each model, reads its depends_on.nodes list
    - Creates one LineageEvent per (model, dependency) pair
      so model A depending on B and C = 2 events

    Args:
        manifest_path: Absolute or relative path to manifest.json

    Returns:
        list[LineageEvent] — one per (model, upstream dependency) pair.
    """
    with open(manifest_path, "r") as f:
        manifest = json.load(f)

    nodes = manifest.get("nodes", {})
    events = []

    for node_id, node in nodes.items():
        # Only process model nodes — skip tests, snapshots, analyses, sources
        if node.get("resource_type") != "model":
            continue

        model_name = node.get("name", node_id)
        schema = node.get("schema", "dbt")
        depends_on_nodes = node.get("depends_on", {}).get("nodes", [])

        if not depends_on_nodes:
            # Model with no dependencies — no lineage edge to create
            continue

        for dep_node_id in depends_on_nodes:
            # dep_node_id looks like: "model.my_project.orders_raw"
            # or "source.my_project.raw_orders"
            # We take the last part as the dataset name
            dep_name = dep_node_id.split(".")[-1]

            event = LineageEvent(
                job=JobRef(
                    name=f"dbt.{model_name}",
                    owner="",
                    orchestrator="dbt",
                ),
                run=RunRef(
                    run_id=str(uuid.uuid4()),
                    status="COMPLETE",
                    start_time=datetime.now(timezone.utc),
                    end_time=datetime.now(timezone.utc),
                ),
                inputs=[
                    DatasetRef(
                        namespace="dbt",
                        name=dep_name,
                        uri=f"dbt://{dep_name}",
                    )
                ],
                outputs=[
                    DatasetRef(
                        namespace="dbt",
                        name=f"{schema}.{model_name}",
                        uri=f"dbt://{schema}.{model_name}",
                    )
                ],
                event_time=datetime.now(timezone.utc),
            )
            events.append(event)

    return events
